//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Exception_ttypes = require('./Exception_types')
var ESmodel_ttypes = require('./ESmodel_types')


var ttypes = module.exports = {};
