//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ttypes.ESFieldTypeEnum = {
  'STRING' : 0,
  'BOOLEAN' : 1,
  'SHORT' : 2,
  'INT' : 3,
  'LONG' : 4,
  'DOUBLE' : 5,
  'FLOAT' : 6
};
